django_book/pystagram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('', index),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

django_book/pystagram/posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/",
         comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
]

django_book/pystagram/users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('signup/', signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),
]

django_book/pystagram/posts/models.py
from django.db import models


class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField(
        "posts.HashTag", verbose_name="해시태그 목록", blank=True)

    def __str__(self):
        return f'{self.user.username}의 Post(id: {self.id})'


class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)


class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

django_book/pystagram/posts/forms.py
from django import forms
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                }
            )
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

django_book/pystagram/posts/views.py
from django.shortcuts import render, redirect
from posts.models import Post, Comment, PostImage, HashTag
from posts.forms import CommentForm, PostForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse


def feeds(request):
    if not request.user.is_authenticated:
        return redirect('users:login')

    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,
    }
    return render(request, 'posts/feeds.html', context)


@require_POST
def comment_add(request):
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.save()

        url_next = request.GET.get("next") or reverse(
            'posts:feeds') + f'#post-{comment.post_id}'
        return HttpResponseRedirect(url_next)


@require_POST
def comment_delete(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if comment.user == request.user:
        comment.delete()

        url_next = request.GET.get("next") or reverse(
            'posts:feeds') + f'#post-{comment.post_id}'
        return HttpResponseRedirect(url_next)
    else:
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다.")


def post_add(request):
    if request.method == "POST":
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            for image_file in request.FILES.getlist("images"):
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            tag_string = request.POST.get("tags")
            if tag_string:
                tag_names = [tag_name.strip()
                             for tag_name in tag_string.split(',')]
                for tag_name in tag_names:
                    tag, _ = HashTag.objects.get_or_create(name=tag_name)
                    post.tags.add(tag)

            url = reverse('posts:feeds') + f'#post-{post.id}'
            return HttpResponseRedirect(url)
    else:
        form = PostForm()

    context = {"form": form}
    return render(request, "posts/post_add.html", context)


def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        posts = Post.objects.none()
    else:
        posts = Post.objects.filter(tags=tag)

    context = {
        "tag_name": tag_name,
        "posts": posts,
    }

    return render(request, 'posts/tags.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()

    context = {
        "post": post,
        "comment_form": comment_form,
    }
    return render(request, "posts/post_detail.html", context)


def post_like(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    if user.like_posts.filter(id=post_id).exists():
        user.like_posts.remove(post)
    else:
        user.like_posts.add(post)

    url_next = request.GET.get("next") or reverse(
        'posts:feeds') + f'#post-{post_id}'
    return HttpResponseRedirect(url_next)

django_book/pystagram/templates/posts/feeds.html
{% extends 'base_slider.html' %}
{% load custom_tags %}

{% block content %}
    <div id="feeds" class="post-container">
        {% for post in posts %}
            {% url 'posts:feeds' as action_redirect_to %}
            {% include 'posts/post.html' with action_redirect_url=action_redirect_to|concat:'#post-'|concat:post.id %}
        {% endfor %}
    </div>
{% endblock %}

django_book/pystagram/templates/posts/post.html
<article id="post-{{ post.id }}" class="post">
    <header class="post-header">
        <a href="{% url 'users:profile' user_id=post.user.id %}">
            {% if post.user.profile_image %}
                <img src="{{ post.user.profile_image.url }}">
            {% endif %}
            <span>{{ post.user.username }}</span>
        </a>

        {% if user != post.user %}
            <form action="{% url 'users:follow' user_id=post.user.id %}?next={{ action_redirect_url }}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">
                    {% if post.user in user.following.all %}
                        Unfollow
                    {% else %}
                        Follow
                    {% endif %}
                </button>
            </form>
        {% endif %}
    </header>

    <div class="post-images splide">
        <div class="splide__track">
            <ul class="splide__list">
                {% for image in post.postimage_set.all %}
                    {% if image.photo %}
                    <li class="splide__slide">
                        <img src="{{ image.photo.url }}">
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="post-content">
        {{ post.content|linebreaksbr }}
        <div class="post-tags">
            {% for tag in post.tags.all %}
                <span><a href="{% url 'posts:tags' tag_name=tag.name %}">#{{ tag.name }}</a></span>
            {% endfor %}
        </div>
    </div>

    <div class="post-buttons">
        <form method="POST" action="{% url 'posts:post_like' post_id=post.id %}?next={{ action_redirect_url }}">
            {% csrf_token %}
            <button type="submit"
                {% if user in post.like_users.all %}
                    style="color: red"
                {% endif %}
            >
                Likes {{ post.like_users.count }}
            </button>
        </form>
        <span>Comment {{ post.comment_set.count }}</span>
    </div>

    <div class="post-comments">
        <ul>
            {% for comment in post.comment_set.all %}
                <li>
                    <span>{{ comment.user.username }}</span>
                    <span>{{ comment.content|linebreaksbr }}</span>

                    {% if user == comment.user %}
                        <form method="POST" action="{% url 'posts:comment_delete' comment_id=comment.id %}?next={{ action_redirect_url }}">
                            {% csrf_token %}
                            <button type="submit">댓글 삭제</button>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
    <small>{{ post.created }}</small>

    <div class="post-comment-create">
        <form method="POST" action="{% url 'posts:comment_add' %}?next={{ action_redirect_url }}">
            {% csrf_token %}
            <input type="hidden" name="post" value="{{ post.id }}">
            {{ comment_form.content }}
            <button type="submit">댓글 달기</button>
        </form>
    </div>
</article>

django_book/pystagram/templates/posts/post_add.html
{% extends 'base_nav.html' %}

{% block content %}
    <div id="post-add">
        <h1>Post 작성</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="id_images">이미지</label>
                <input id="id_images" name="images" type="file" multiple>
            </div>
            {{ form.as_p }}
            <div>
                <label for="id_tags">해시태그</label>
                <input id="id_tags" name="tags" type="text"
                    placeholder="쉼표(,)로 구분해 태그 입력">
            </div>
            <button type="submit">게시글 추가</button>
        </form>
    </div>
{% endblock %}

django_book/pystagram/templates/posts/post_detail.html
{% extends 'base_slider.html' %}

{% block content %}
    <div id="feeds" class="post-container">
        {% url 'posts:post_detail' post.id as action_redirect_to %}
        {% include 'posts/post.html' with action_redirect_url=action_redirect_to %}
    </div>
{% endblock %}

django_book/pystagram/templates/posts/tags.html
{% extends 'base_nav.html' %}

{% block content %}
    <div id="tags">
        <head class="tags-header">
            <h2>#{{ tag_name }}</h2>
            <div>게시물 {{ posts.count }}</div>
        </head>
        <div class="post-grid-container">
            {% for post in posts %}
                {% if post.postimage_set.first and post.postimage_set.first.photo %}
                    <a href="{% url 'posts:post_detail' post_id=post.id %}">
                        <img src="{{ post.postimage_set.first.photo.url }}" alt="">
                    </a>
                {% endif %}
                {% empty %}
                    <p>게시된 게시물이 없습니다.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}